permalink: :title

highlighter: rouge
markdown: kramdown

title : RTPI Jumbotron
tagline: Interactive Display

production_url : labs.orbitist.com/rtpi-jumbotron

baseurl : /rtpi-jumbotron

timezone : America/New_York
